# Some applications do not have proper authentication in themselves, for these we can use oath2-proxy with Azure AD to authenticate.
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oauth2-proxy-all
  namespace: oauth2
spec:
  releaseName: oauth2-proxy-all
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: oauth2-proxy
    version: 3.2.2
  values:
    serviceAccount:
      enabled: false
    replicaCount: 1
    extraArgs:
      provider: azure
      azure-tenant: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
    config:
      existingSecret: oauth2-proxy-all
    service:
      port: 4180
