---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: infrastructure
spec:
  releaseName: external-dns
  values:
    domainFilters: ["dev.sdpaks.equinor.com"]