# To eliminate the bureaucracy and manual labour of getting and maintaining official DigiCert Equinor SSL certificates we use
# CertManager to create Lets Encrypt certificates. For the most part we use HTTP01 as our validation.
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infrastructure
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: 0.9.1
  values: 
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: ClusterIssuer