---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy-helmRelease-name
  namespace: staging
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: oauth2-proxy-releaseName
  chart:
    git: ssh://git@github.com/Statoil/sdp-flux.git
    ref: oauth2-proxy
    path: custom-charts/sdp-oauth2-proxy
  values:
    replicaCount: 1
    container:
      args:
        azure_tenant: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
      env:
        OAUTH2_PROXY_CLIENT_ID: 44955838-424e-4bd3-aa0b-effd83160573
        OAUTH2_PROXY_CLIENT_SECRET: ..:R[Ak]eF>[V#;^]rz(I!e7:8@(H
        OAUTH2_PROXY_COOKIE_SECRET: fHEksmahJbgbYZVGL9gC+w==
