apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret-envs
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgCMwro8QLN1Bz8kunPNqKMiysQedGOTpRNd7fvUD0e2hNTEoOqY6o1C526hYWHd9sOva2ZHGIvXX4RVx6FQSfrDpUiHI3dmA2/Ulb0x0cI5Px0COLSpKYW1tA0j8pZFMCFXjJJBRExQlgs28Mxg6B15qWon2nVLR3z32BDszGD3R+0jPWUo8viq+DKX3EGkluciRIKwsqIjsud1z2kMquTiX1tmdIQV94uBXK2+vvSyEA80g0R9hmVnCH1zk06cBDZqHT1jPuNnWauTQw51rTPwLiLH5MxTZeLguH6ATDBvvW6IsgGH5HRwMlavGKNlNWvGkcUipe8c5RINJ1yJYcYTRyC9grMojlXulFzjmeSsBf58yP2KXMq5U0DbeVqtjwGQAb3DZqTroLcZR1FD5B3TkiaYMJIakJwxPO9yOZH87MoIt9aB9SGNSn9w53RK6xW7cPZfpVDwKnyVy/9CV+bVIkM163nKj15ik7LlD3lDf608Rv0Q9tunpfLJUw75GBwaLLcHWZqD6Rp1a6BUdrw/QwVC2mJuPVXFparMPWRshwHeG5t/kbeUCiVW6ul9EDAzAyPOgP5AtgXVAlZP6zwgehzi35BIM+KrEO1PXaqBhKH9p2eS2RJMrSAxt5HXcUI5M96ix12ZotnRaEh7arkN87rywsNLlFvUo/Bh6+iLcPxNRzkiFlCg1ch8DsfM5pOqR8dnY3XSFqEbYfK4FmmpHqGX1Fv61qFQMvnyFwWsoypr5V9D/XnSUDF/bg==
