apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlabstats-git-key
  namespace: monitoring
spec:
  encryptedData:
    GIT_PRIVATE_TOKEN: AgAOS042afengrAnXeMNc7tmgQmnZGX/7tm1kL/fUAW+fuLJjf2150Y2Vz/B6KUjvlrGu+XxkPougRrckUrJB29lezs/AqEqnanRpAu8MVuitfECg6oddMTMLrFBsinxdcNf2VDddtViFl+2lzUn1ByT7cgmGShGg+zIjm5S7S5Ng9AMlNp+u1AaMzLmZoPxtbo+S259in6AnwsCU4+XtXOJn0odSVZkmyVPmGy4/405J0U555ycIPEHzvYuUcXe8BGY6ktgPSueAgU1QvMTlwFUffjCzG3DWjIe1EyPj5P2NqYmnFc1mnkNovfs9EHW8Z3pj1EAwP2AVBI71vji98IqyWo1NK+nXhQw9+Mq5chupLRXCAlOhwsDmgGMutLh/zEDMWU6XoR46QDnZ7kPS2GoxKiQtTX7ZkH4T71cH/MCJzXbppbQOOyub5tX3S48CaI1DdtsrdKr9Hug0MZXZUaPyINYpVwQFRVgK6C+Z2vZu6zuqaxOkH8OMWY5VGjt9JjnIHhLGLYIS1SLmqN9dncA1o4wZDXEnuOK4WaERHywz0utlz0Z/NECuvb8tJchZP5iVf00bUc9Ty/K/sFoWMEfsQZAYFeyOEVt/O+XkDXfUKX+Gj0DsZfe5a75BL1JIhxJpJSqoiYcFNRZ+fGdpNy1G6JMLswkLDip4kwEzLcrzL5S6Uu8uwJd9FDLqddKwXUrewW8tntD6H/HoB+24zESKgN3sA==
  template:
    metadata:
      name: gitlabstats-git-key
      namespace: monitoring
