apiVersion: v1
kind: Service
metadata:
  name: gitlabstats
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: gitlabstats
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
