apiVersion: v1
kind: Service
metadata:
  name: gitlabstats
  namespace: monitoring
  labels:
    metric-scrape: prometheus
spec:
  selector:
    app: gitlabstats
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 5000
