---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aware-api
  namespace: aware
spec:
  template:
    spec:
      containers:
      - name: aware-api
        env:
        - name: PROMETHEUS_API
          value: "http://prometheus-operator-prometheus.monitoring:9090/api/v1/alerts"
        - name: DEPLOYMENT_NAME
          value: "SDPAKS-Development"
        - name: IGNORE_PROMETHEUS_ALERTS
          value: "CoreDNSDown,KubeAPIDown,KubeControllerManagerDown,KubeSchedulerDown,KubeletDown,TargetDown,KubeAPIErrorsHigh,Watchdog"
