apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aware
  namespace: aware
spec:
  tls:
    - hosts:
        - aware.dev.sdpaks.equinor.com
      secretName: aware-tls
  rules:
    - host: aware.dev.sdpaks.equinor.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aware-web
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: aware-api
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aware-auth
  namespace: aware
  labels:
    app: aware
spec:
  tls:
  - hosts:
    - aware.dev.sdpaks.equinor.com
    secretName: aware-tls
  rules:
    - host: aware.dev.sdpaks.equinor.com
      http:
        paths:
          - path: /oauth2 
            pathType: Exact
            backend:
              service:
                name: oauth2-proxy-sdp
                port:
                  number: 4180
