---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-nfs
  namespace: nfs-provisioner
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
