apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-basic-auth
  namespace: loki
spec:
  encryptedData:
    auth: AgDNf7TbmKuaWxZywRWlwBwhRhFnYiwJxE1kpKLnpzNoRNbwrVG/k+IZHf7cjitJUrQXJt2JemdFDnUdI7KQr+cbTiRRBbdBKa4y5xH9PWhXU0OaLjcKnIWFn1ro1o6zu5U/l5rcCDm7eoqEvclB4a2dutWektLZ81AapTEy1PPq8OSufsop5dj0AI0hqMqVsK9Hr2zC/yC6RDcGIZ/ruvVPZz9O6x0fXyVTH8RIwdeHVCCAvfwYSbK+1l7BstLT53E+W1Mn9n4/J9sH4y/VAtTnXwcZ/khTkI+bNVBdCXzuboZG3BWhvM02Wj1IDdPazxhaagCb/LVbh404xwpD3/9Cpa9V7y68juflhyo6V0wm5R9vXJAp74/ZrljUyL6vhL/KRM7xWNANEV/Q/hbsJ6MYvVDvK73k+/0KHFrdUgoQBZvSxF6pVwzzx5auJkR0T78O9hOxJuuXOyowvPReFMwTWGJF/25paa6BgYd8Hn/i1i4vtXquZHxknpbGTzFG6Ub0LZOMyWRikKQMdR2IIV7FBtiBpPohgh9jhofHGjqYf8H5YqwT2X0ERv37tWnLG+xs9jITkHVG1ZlJ7JfJF2CBdFn7ppt13oLPNvA2yGhr/5ryKV808CZt3tT5GVHM7wQNH1BhgQHP6QXCe32FWCdd8hU6gex3839jZAzn2hrK5I5/PN/87FX3x3mFY2NDGN6vmU64WuR/JMBozI4OwHniUXNM04S3otEI2xiV5UJALK72CQ42xZ3wHgcE1S6W
  template:
    metadata:
      creationTimestamp: null
      name: loki-basic-auth
      namespace: loki

