apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-basic-auth
  namespace: loki
spec:
  encryptedData:
    auth: AgA5RXnoXdxoFXMtW6HXjGVVA9Yh5D8e5cZY5eVQLoGAMEhZDy+HuAHPZ31s/D350ex1XS0AG3uaHqaXrJhnlOY/UwNL2qv8HddVwvHRmYaR+zEQj/aBbHT7/GiBcaRpU6M3cy7Vgx9Mw+3/uZrJTPm5mtPT97U3YaOmP4IgRiUDXrslAkVHoE/jPYdsIrdl9sR+5bOHp38e6IQQDM3Yd35YMRZ9RbgHPjoNCDUL+COiESO0AHRGdPyQZ9VfMYYI4k9wiJc8e2AucyJjpIgpjkoTt6RKoOwz7bETrXCrhWnZxzJnmnhv8kcy6pJa/Qycm4rC5q5fykMhsRlgu9dic0aqVzgYJiWns5Fw/PGllb4mA5ahmHREbXcewlSugeYzIpxeWUq0aaPDoTTaZi225wqH+25pNkoK4ACo2RDOpj6TufRJ/co/zgJYKk0GHscvO5o1iORfB2Jq2NNJF9M8EbCCmcBdo++H43TYkf25juZlrsmxBk9mUPTpYwkCFCXANaphP+E8K5Yx1SsCNyIO9b7V2W7UnFt5s5B06/kP0ZB6CnKbyH2GmgNpciYDitvc22pbJHVcW0oVvYrQFAqrLfc8pmvaJYiforFkf4+Y0oyGvpwze81qUkGn0oLSW6M+dkK5ZrffzJ6Xh0hTHb5fIO/EZePDwdaNWkhxILF3zyFs8ELdjWVCHaYjDt72szpJ0RoGK7kVQFosvD7jzV5f9ESUcr5IXHiy+kQxy6BCGw==
  template:
    metadata:
      creationTimestamp: null
      name: loki-basic-auth
      namespace: loki
status: {}

