# How to manage secrets in a GitOps environment? Use one of the big Vault providers, or use asyncron encrypted secrets with
# Sealed Secrets. The latter is our choice until we need the complexity from the big ones.
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: loki
spec:
  releaseName: loki-stack
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki-stack
    version: 2.0.2
  values:
    config:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 720h
    loki:
      persistence:
        enabled: true
        size: 100Gi
        storageClassName: managed-premium-retain-nocache
    fluent-bit:
      enabled: false
    promtail:
      enabled: true
