apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hgir-secrets
  namespace: prod
spec:
  encryptedData:
    APP_SECRET: AgCe8mC7WfrV2RPTVk7d8Tn3us178Ro2jz0DXg2AYRQw3X1cLv/SQg+Jjxa6sWuaGFjBlnGssNTEj16RFHwfW8TsxvKw1ghgjexEjaqatp5+a6vYulNlj/8KxuRMI77B5WCR492kbvLp0ve+0oPvXUfBcc0/a+kHLK+g/cftJBT1jpFYejsRUJwufxbQAizqPAsXPHa93uP+KMAKFyMMK99VNawGbNgkSRR1/PvURIY7XQGmI68lJbA9ersPzY5fBME9sYNyOX7cLnkM8LzxVtr5DKOVK60uOBIj2uoYuPv72cXO3NIHpvlM69h6DnK7dXK7LhuY0hPW9YZ056XhzJBskNy4LWfJOVXjxMRLvJut18Dx28Z9TYS+auNwkHnBZp4Cv7wsmUdB/8Gd9LDQDv86v8LERhy47lO/fJkBNg+YLKUIkVkjGy4gyUvhhgF/Ws8vbTkYsyrFKrbwfU3NziUXb5/SEErWjvN4/mwxTDivlDg3e6yR5USlKf524CHX5ZMiAuCF1RSFYP8cu1NGI3oQSVAc905qnW8Dn7sEYZvqaDZOiHQUkGm5p8v/OZr4a0M/+UhswKi+Gx1XylYgMEQ3dUh8wjeRkMlrmiVwPRyMxfDXduQsZoeYd0m7kT0KaRrETcjx6byZHowiNdqEauGYvnGlYfRC+MYvn5iO/WFafcnNG//Xw/4DN90CuzTz8DXwxW/4oqPKqyAACovAFAeah5QzYChw0qE1TkU1pTjBh3yy+b/4BAez
    DATABASE_PASSWORD: AgCNJwIEqvb37igDzQrjK3p7BtBdiFcoAkqCjzhf9SiD46pqeL2DLXUFzUXzYyptbQA+E/8VqAQyZJuqcnYr7MpZRqbuMAX3QHIRQayzDvEoQXcKDVtZzSXYnhuDdx7uZzoC+Euuw9YkcjejHh970NiwZ7NK1tUrn/ucJkYDXy2VW+RaiEIMWXxAhB0s9s+7aeC3FfIJbgsEyx835WIILyCb+97i5XgpNB6B7p04l/6dRTzxXKunxu92ZpX+fwLfFipSMqJ6rIxI82DI7RGXya/sOuh2NimvapuGtxvM9BAQLwvqYaXraBx5qso9kXQ/LhtDWOhEP9NPdaL05XVSOOnlZY1ZdfeHpsmzJ86rOYwb+I7YznWo9+07E++kg+MAE7brzoUuHpcQ7K4FSn3EUCISEdl/OshqPnQNzomDkHEfkPh8ZF3RjK/EjgSb4BOU50uuZUPz0eBgrz7cohKrkVBQqxFxeHWr8WOJSLX43MEu8OrgGWn5HY9/Qe06yw7JzcHWVW1MWjgLmWDSWwADKH3iyBSK0sKcdrbze0lCqxHJTZc8ngP79WNG0kVk8j3EtGZO+09TNBX6GAj+nswuk+IwlC2fQ0PkNIgIfyL82BZrCW73/CPmi4nuNcCbGwLdPmJtDqgrwvTSpIuvZfyVIYfaYX63OBUk7QaH2JnYcpB9aoTb7WJmBbO4vtZmdS3OhzAlNC1XxeFHbnOa39j+VJxq2Z5vVw==
  template:
    metadata:
      creationTimestamp: null
      name: hgir-secrets
      namespace: prod
