apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hgir-secrets
  namespace: prod
spec:
  encryptedData:
    APP_SECRET: AgDm3u4O6J1Z/FIqoE8o6ElO+N2EPQjQK1+/wd0vaTHcr7770W8oI8WajvvhvOpsvBmLiBK0AOtKK+jLyRMYpMM2pkIxGIqQ/OjY53XVZ4S8rtBDEGYa7SYi2T9RA0kHlWhSjnD+BPWk1qyFXJUAnghQHEC164f2aKv/0Z4s8B6z/SHxE0kKfnBicHEPy64q9G4N1vsyG7LpuYfJc9/f3QwKxBZOBEDJWgggnSXTU881l5xcm3s2hluKI11FpFKGFHSNASCaZfdFAZhCdd/aZXGbAS/5Im+ZTbNqwn+1aF2KD+EkJiWAwyi3Ksid4EeTCsoqRkCTrKr9kTgWyP9MdAS/VGhSbzlmybyGtDYYf36oYCxciOmIGQ3TLaYbeg1BNTpGj7Y+BeVEaxfGH9HVHmheYkJXLfWjwv5bEQv+/OKkE8LQkX+ThLmdjnWAsFkrnFR2s3Ue4HPTRnylRJaruQTS9D+QhzDsor1EQagpmYZfjwDAQ1u13DGp+Rx1GZa3PyFEwvwfePfXPoVlMJoq6gU7PX0lMzjJrw6BOzUbwoolUKkIeYcBZphgf9JwhxRGP4PLBzwh5877TA1c+q/+kjiPEnz8MTIUrvA8jzsBDIzx8+AoBzM4bbiUHhczROYwdxINPEHx1C4qHQH/OtlH6gy/+5/zV3hspauDfw4o6wb7nFDdVJ4YeNfS/ZSW6aLdoTMjbVUsLKmdybi66/BiGEMfeGShP93Rbt9yfkuBnX0YvAxn
    DATABASE_PASSWORD: AgCsGz+9hfvRKDuf/DsRRk5uLdDPP0/SmOUmJN6PHW3kB3YzyRuI/L7YsWBTKjZ6PhdW+N+ymO3eCT5hywxaI7ybkH8Fy43/eD//6p+jJziCJ7k7GUl/qzQgvd5kr00UY7ioewMBoZo4++nMpYFo68ddIQ7Cmf366IqL4HP1Yhe2oKel58cGya5OeBK/eiOBgE3eKsRSIYBb6/Du8IgJCQxL0oZD35jwhVTN+//LMVigq4JJWfbo3knx0Mc0DGnXPnBBJBiNh8oFfnpjKiuPfyctZIFWvN1iXbH6GXt163VpYcobmEV0Cd/r5Jskj+vJMzsg0/0JuSVlLBVIcDX5wGT0Quq6a9ggLVYIodsx4vsXrqCE+apKaT5Skvi7CfSNXqqILHca68uPwvxUVeFUCard9+cgFwg1sXQdF4MTpInXzIIi6s9W38wgiVKEZ3R6Scw0Lj1wOPk49VsXbcNySxuouvBbOFGyJ3n7/A9ZRcpSM1wapTUC0OTyzm6PA6wvHu+Et3iyWAuwkTn65YL3Kf+gRtdmLxKMC9IKsJwYQUjUmavVWj5boxPtdofnfRNasA+KSEnQh74gD7it3VuBaeUshR68WOcBwT7nocC+m3/yPcjMWMl7J8xZN2ibuBxY42ps00trbQC7UhGVtkD2NOrmTqVgKxj21TNvUZ/8R8JXt+0+09TdbGa0ezkB//OXLJVnYTLXvM/dElVIReC+BR/TwDNbIQ==
  template:
    metadata:
      creationTimestamp: null
      name: hgir-secrets
      namespace: prod
