---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sdp-oauth2-proxy
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: sdp-oauth2-proxy
  chart:
    git: ssh://git@github.com/Statoil/sdp-flux.git
    ref: oauth2-proxy
    path: custom-charts/sdp-oauth2-proxy
  values:
   