---
language: C

env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TAR=helm-v2.12.3-linux-amd64.tar.gz
    - KUBEVAL_URL=https://github.com/instrumenta/kubeval/releases/download/0.10.0/
    - KUBEVAL_TAR=kubeval-linux-amd64.tar.gz

install:
  - wget -q ${KUBEVAL_URL}/${KUBEVAL_TAR}
  - tar xzfv ${KUBEVAL_TAR}
  - wget -q ${HELM_URL}/${HELM_TAR}
  - tar xzfv ${HELM_TAR}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only

script:
  - >
    fileList=$(find "$(pwd -P)" -not -path "*/custom-charts*" -type f \( ! -iname ".flux.yaml" \) -name *.yaml -exec grep -L -H |'apiVersion: flux.weave.works/v1beta1\|apiVersion: bitnami.com\|apiVersion: certmanager.k8s.io\|apiVersion: kustomize.config.k8s.io/v1beta1' {} \;) 

     for chart in `ls ./custom-charts`; do
      helm lint ./custom-charts/${chart}
      if [ $? != 0 ]; then
       travis_terminate 1
      fi
     done

      ./kubeval $fileList
      if [ $? != 0 ]; then
       travis_terminate 1
      fi
