apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  releaseName: gitlab-minio
  chart:
    git: git@github.com:equinor/sdp-flux.git
    ref: dev
    path: custom-charts/minio
  values:
    existingSecret: gitlab-minio-secret
    azuregateway:
      enabled: true
      replicas: 2
    ingress:
      annotations:
        kubernetes.io/tls-acme: true
      enabled: true
    tls:
      enabled: true
      certSecret: gitlab-minio-tls