---
apiVersion: v1
kind: Service
metadata:
  name: release-aware-web
  namespace: monitoring
spec:
  selector:
    app: release-aware
    tier: web
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000

