---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: v1
kind: Namespace
metadata:
  name: aware
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    # https://cert-manager.readthedocs.io/en/latest/getting-started/webhook.html#disabling-validation-on-the-cert-manager-namespace
    certmanager.k8s.io/disable-validation: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: verdaccio
