# Update with `kustomize edit add patch ./**/*.yaml`
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base/
resources:
- ./gitlab/gitlab-sdp-tls.yaml
- ./gitlab/ingress.yaml
- ./gitlab/gitlab-azure-saml.yaml
- ./velero/prod-storagelocation.yaml
- ./namespaces/backup-sandbox.yaml
patchesStrategicMerge:
- ./sdp-web/ingress-patch.yaml
- ./gitlabstats/deployment-patch.yaml
- ./sensu/ingress-patch.yaml
- ./aware/ingress-patch.yaml
- ./aware/api-deployment-patch.yaml
- ./monitor/ingress-patch.yaml
- ./prometheus-operator/auth-ingress-patch.yaml
- ./prometheus-operator/helm-release-patch.yaml
- ./release-aware/ingress-patch.yaml
- ./verdaccio/helm-release-patch.yaml
- ./matomo/helm-release-patch.yaml
- ./external-dns/helm-release-patch.yaml
- ./velero/helm-release-patch.yaml
- ./hgir/ingress-patch.yaml
- ./nginx-ingress/helm-release-patch.yaml
- ./gitlab/helm-release-patch.yaml
- ./loki/ingress-patch.yaml
