# Update with `kustomize edit add patch ./**/*.yaml`
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base/
resources:
- ./gitlab/gitlab-azure-saml.yaml
- ./velero/prod-storagelocation.yaml
- ./velero/default-storagelocation.yaml
patchesStrategicMerge:
- ./verdaccio/helm-release-patch.yaml
- ./external-dns/helm-release-patch.yaml
- ./velero/helm-release-patch.yaml
- ./hgir/ingress-patch.yaml
- ./hgir/deployment-patch.yaml
- ./nginx-ingress/helm-release-patch.yaml
- ./gitlab/helm-release-patch.yaml
- ./loki/ingress-patch.yaml
- ./ms-continuus/cronjob-patch.yaml
