kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: hgir
  name: hgir-db
  namespace: dev
spec:
  storageClassName: azure-disk-uid-70
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi