apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: hgir
    kubernetes.io/cluster-service: "true"
  name: azure-disk-uid-70
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: Premium_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - uid=70
  - gid=70
  - dir_mode=0755
  - file_mode=0644
