---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: infrastructure
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 0.20.0
  values:
    controller:
      ingressClass: nginx
      publishService:
        enabled: true # Ref: https://github.com/kubernetes-incubator/external-dns/blob/master/docs/faq.md#why-is-externaldns-only-adding-a-single-ip-address-in-route-53-on-aws-when-using-the-nginx-ingress-controller-how-do-i-get-it-to-use-the-fqdn-of-the-elb-assigned-to-my-nginx-ingress-controller-service-instead
      stats:
        enabled: false # Turn on after enable Prometheus
      metrics:
        enabled: false # Turn on after enable Prometheus
      service:
        enableHttp: true # Turn off?
      externalTrafficPolicy: "Local"
