---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: cert-manager
  namespace: infrastructure
  labels:
    chart: cert-manager
  annotations:
    flux.weave.works/automated: "true"
spec:
  chartGitPath: cert-manager
  releaseName: cert-manager
  values: 
    ingressShim:
      defaultIssuerName: letsencrypt-staging
      defaultIssuerKind: ClusterIssuer