---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infrastructure
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: cert-manager
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: cert-manager
    version: 0.5.1
  values: 
    ingressShim:
      defaultIssuerName: letsencrypt-staging
      defaultIssuerKind: ClusterIssuer