---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: infrastructure
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: external-dns
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: external-dns
    version: 0.5.7
  values:
    provider: azure
    azure: 
      secretName: azure-dns-config-file
    domainFilters: [$(DOMAIN_FILTER)]
    extraEnv: 
      - name: DOMAIN_FILTER
        valueFrom:
          configMapKeyRef:
            name: external-dns
            key: domain-filter
    rbac:
      create: true