---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  releaseName: sealed-secrets
  chart:
    git: git@github.com:Statoil/sdp-flux.git
    ref: master
    path: custom-charts/sealed-secrets
  values:
    image: quay.io/bitnami/sealed-secrets-controller:v0.7.0