kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: hgir
  name: hgir-db
  namespace: prod
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi