# Azure makes sure to patch security updates on our AKS nodes, but does not ensure these updates are applied.
# To apply these updates we need to reboot the nodes, our solution to this is to use Kured.
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kured
  namespace: infrastructure
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: kured
  chart:
    repository: https://weaveworks.github.io/kured
    name: kured
    version: 2.5.0
  values:
    updateStrategy: RollingUpdate
    configuration:
      period: 10m0s
      rebootDays: [mo,we,fr]
      slackUsername: "SDPTeam Kured"
      slackChannel: "sdpteam-team"
      slackHookUrl: $(SLACK_WEBHOOK)
      blockingPodSelector: ["app=ms-continuus"]
      timeZone: "Europe/Oslo"
      startTime: "03:30"
      endTime: "04:30"
    extraEnvVars:
    - name: SLACK_WEBHOOK
      valueFrom:
          secretKeyRef:
            name: kured-webhook
            key: token
