# Azure makes sure to patch security updates on our AKS nodes, but does not ensure these updates are applied.
# To apply these updates we need to reboot the nodes, our solution to this is to use Kured.
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: infrastructure
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: kured
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kured
    version: 1.5.0
  values:
    updateStrategy: RollingUpdate
    extraArgs:
      period: 10m0s
      reboot-sentinel: "/var/run/reboot-required-night"
      slack-username: "SDPTeam Kured"
      slack-hook-url: secrets.kured-webhook.token #Needs to be set outside Git. how to get to secret?
      blocking-pod-selector: app=task-runner,release=gitlab
      time-zone: "Europe/Oslo"
      start-time: "01:30"
      end-time: "04:30"
