# How to manage secrets in a GitOps environment? Use one of the big Vault providers, or use asyncron encrypted secrets with
# Sealed Secrets. The latter is our choice until we need the complexity from the big ones.
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  releaseName: sealed-secrets
  chart:
    git: git@github.com:equinor/sdp-flux.git
    ref: master
    path: custom-charts/sealed-secrets
  values:
    image: quay.io/bitnami/sealed-secrets-controller:v0.8.1