# Performance metrics to get insight in the clusterstatus. Supports alerts to get notified if something goes avry.
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  values:
    alertmanager:
      ingress:
        hosts:
        - alertmanager.sdpaks.equinor.com
        tls:
        - secretName: alertmanager-tls
          hosts:
          - alertmanager.sdpaks.equinor.com

    grafana:
      env:
        GF_SERVER_ROOT_URL: https://grafana.sdpaks.equinor.com
      ingress:
        hosts:
        - grafana.sdpaks.equinor.com
        tls:
        - secretName: grafana-tls
          hosts:
          - grafana.sdpaks.equinor.com

    prometheus:
      ingress:
        enabled: true
        hosts:
        - prometheus.sdpaks.equinor.com
        tls:
        - secretName: prometheus-tls
          hosts:
          - prometheus.sdpaks.equinor.com
