# Private web analytics solution
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: matomo
  namespace: prod
spec:
  values:
    ingress:
      hosts:
      - matomo.sdpaks.equinor.com
      tls:
      - secretName: matomo-tls
        hosts:
        - matomo.sdpaks.equinor.com
