---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: elasticsearch-curator
  namespace: monitoring
  annotations:
    flux.weave.works/automated: false
spec:
  chart:
    name: elasticsearch-curator
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.0.1
  releaseName: elasticsearch-curator
  values:
    config:
      elasticsearch:
        hosts:
          - elasticsearch-client
        port: 9200
    configMaps:
      action_file_yml: |-
        ---
        actions:
          1:
            action: delete_indices
            description: "Clean up old Metricbeat indicies"
            options:
              timeout_override:
              continue_if_exception: False
              disable_action: False
              ignore_empty_list: True
            filters:
            - filtertype: pattern
              kind: prefix
              value: 'metricbeat-'
            - filtertype: age
              source: name
              direction: older
              timestring: '%Y.%m.%d'
              unit: days
              unit_count: 14
          2:
            action: shrink
            description: "Compress old Metricbeat indicies to save space"
            options:
              ignore_empty_list: True
              shrink_node: DETERMINISTIC
              node_filters:
                permit_masters: False
                exclude_nodes: ['not_this_node']
              number_of_shards: 1
              number_of_replicas: 1
              shrink_prefix:
              shrink_suffix: '-shrink'
              delete_after: True
              post_allocation:
                allocation_type: include
                key: node_tag
                value: cold
              wait_for_active_shards: 1
              extra_settings:
                settings:
                  index.codec: best_compression
                  index.mapping.total_fields.limit: 10000
              wait_for_completion: True
              wait_for_rebalance: True
              wait_interval: 9
              max_wait: -1
            filters:
            - filtertype: pattern
              kind: prefix
              value: 'metricbeat-'
            - filtertype: age
              source: name
              direction: older
              timestring: '%Y.%m.%d'
              unit: days
              unit_count: 3
            - filtertype: pattern
              kind: suffix
              value: '-shrink'
              exclude: True
          3:
            action: delete_indices
            description: "Clean up old Filebeat indicies"
            options:
              timeout_override:
              continue_if_exception: False
              disable_action: False
              ignore_empty_list: True
            filters:
            - filtertype: pattern
              kind: prefix
              value: 'filebeat-'
            - filtertype: age
              source: name
              direction: older
              timestring: '%Y.%m.%d'
              unit: months
              unit_count: 6
          4:
            action: shrink
            description: "Compress old Filebeat indicies to save space"
            options:
              ignore_empty_list: True
              shrink_node: DETERMINISTIC
              node_filters:
                permit_masters: False
                exclude_nodes: ['not_this_node']
              number_of_shards: 1
              number_of_replicas: 1
              shrink_prefix:
              shrink_suffix: '-shrink'
              delete_after: True
              post_allocation:
                allocation_type: include
                key: node_tag
                value: cold
              wait_for_active_shards: 1
              extra_settings:
                settings:
                  index.codec: best_compression
                  index.mapping.total_fields.limit: 10000
              wait_for_completion: True
              wait_for_rebalance: True
              wait_interval: 9
              max_wait: -1
            filters:
            - filtertype: pattern
              kind: prefix
              value: 'filebeat-'
            - filtertype: age
              source: name
              direction: older
              timestring: '%Y.%m.%d'
              unit: days
              unit_count: 7
            - filtertype: pattern
              kind: suffix
              value: '-shrink'
              exclude: True
