---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  annotations:
    flux.weave.works/automated: false
  name: metricbeat
  namespace: monitoring
spec:
  chart:
    name: metricbeat
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.4.0
  releaseName: metricbeat
  values:
    image:
      repository: docker.elastic.co/beats/metricbeat
      tag: 6.5.4
    daemonset:
      config:
        setup.dashboards.enabled: true
        setup.kibana:
          host: "kibana:443"
        metricbeat.autodiscover:
          providers:
          - type: kubernetes
            host: ${NODE_NAME}
            hints.enabled: true
        output.file: nil
        output.elasticsearch:
          hosts: ["elasticsearch-client:9200"]
    deployment:
      config:
        setup.dashboards.enabled: true
        setup.kibana:
          host: "kibana:443"
        metricbeat.autodiscover:
          providers:
          - type: kubernetes
            hints.enabled: true
        output.file: nil
        output.elasticsearch:
          hosts: ["elasticsearch-client:9200"]
      modules:
        nginx-ingress:
          enabled: true
          config:
            - module: prometheus
              metricsets: ["collector"]
              period: 10s
              hosts: ["nginx-ingress-controller-metrics.infrastructure:9913"]
              metrics_path: /metrics
              namespace: infrastructure
            - module: nginx
              metricsets: ["stubstatus"]
              period: 10s
              hosts: ["nginx-ingress-controller-stats.infrastructure:18080"]
              server_status_path: "nginx_status"
