kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: hgir
  name: hgir-db
  namespace: prod
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: sysdig-inspect
  name: sysdig-inspect
  namespace: falco
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi