---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: verdaccio
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: verdaccio
    version: 0.5.0
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        external-dns.alpha.kubernetes.io/hostname: verdaccio.sdp.handlel.app.
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
      hosts:
      - verdaccio.sdp.handlel.app
      tls:
      - secretName: verdaccio-sdp-handlel-app-tls
        hosts:
        - verdaccio.sdp.handlel.app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: infrastructure
spec:
  rules:
  - host: verdaccio.sdp.handlel.app
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
  tls:
  - hosts:
    - verdaccio.sdp.handlel.app
    secretName: verdaccio-sdp-handlel-app-tls