---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: matomo-auth
  namespace: prod
spec:
  tls:
  - hosts:
    - matomo.dev.sdpaks.equinor.com
    secretName: matomo-tls
  rules:
    - host: matomo.dev.sdpaks.equinor.com
      http:
        paths:
          - path: /oauth2 
            backend:
              serviceName: oauth2-proxy-sdp
              servicePort: 4180
