apiVersion: v1
appVersion: "1.0"
description: A Kubernetes controller and tool for one-way encrypted Secrets
name: sealed-secrets
version: 0.1.0
home: https://github.com/bitnami-labs/sealed-secrets
sources:
- https://github.com/bitnami-labs/sealed-secrets
maintainers:
  - name: stefanprodan
    email: stefanprodan@users.noreply.github.com
engine: gotpl
