---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  values:
    gitlab:
      webservice:
        ingress:
          tls:
            secretName: gitlab-sdp-tls
          annotations:
            kubernetes.io/tls-acme: "true"
    global:
      psql:
        database: postgres
        host: sdpaks-dev-gitlab-psql13.postgres.database.azure.com
        password:
          key: password
          secret: gitlab-postgres-secret
        username: gitlab
      hosts:
        domain: dev.sdpaks.equinor.com
        gitlab:
          name: gitlab.dev.sdpaks.equinor.com
        registry:
          name: registry.dev.sdpaks.equinor.com
      ingress:
        class: nginx
        annotations:
          kubernetes.io/tls-acme: true
        configureCertmanager: false
