apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  releaseName: gitlab-minio
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minio
    version: 3.0.2
  values:
    existingSecret: gitlab-minio-secret
    azuregateway:
      enabled: true
      replicas: 2
    extraArgs: 
    - "--compat"