---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  values:
    gitlab:
      task-runner:
        backups: # test for dev
          cron:
            enabled: false
            schedule: 45 1 * * *
            extraArgs:
              "--skip artifacts --skip registry --skip uploads --skip lfs"
    global:
      psql:
        database: postgres
        host: sdpaks-prod-gitlab-psql11.postgres.database.azure.com
        password:
          key: password
          secret: gitlab-postgres-secret
        username: gitlab@sdpaks-prod-gitlab-psql11
      hosts:
        domain: sdp.equinor.com
        gitlab:
          name: gitlab.sdp.equinor.com
        registry:
          name: registry.dev.sdpaks.equinor.com
      ingress:
        class: nginx
        annotations:
          kubernetes.io/tls-acme: true
        configureCertmanager: false