---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  values:
    gitlab:
      task-runner:
        backups: # test for dev
          cron:
            enabled: false
            schedule: 45 1 * * *
            extraArgs:
              "--skip artifacts --skip registry --skip uploads --skip lfs"
      webservice:
        ingress:
          tls:
            secretName: gitlab-sdp-tls
          annotations:
            kubernetes.io/tls-acme: "true"
    global:
      psql:
        database: postgres
        host: sdpaks-dev-gitlab-psql11.postgres.database.azure.com
        password:
          key: password
          secret: gitlab-postgres-secret
        username: gitlab@sdpaks-dev-gitlab-psql11
      hosts:
        domain: dev.sdpaks.equinor.com
        gitlab:
          name: gitlab.dev.sdpaks.equinor.com
        registry:
          name: registry.dev.sdpaks.equinor.com
      ingress:
        class: nginx
        annotations:
          kubernetes.io/tls-acme: true
        configureCertmanager: false
