---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  values:
    gitlab:
      task-runner:
        backups: # test for dev
          cron:
            enabled: true
            schedule: 45 1 * * *
            extraArgs: ""
    global:
      psql:
        database: postgres
        host: sdpaks-dev-gitlab-psql.postgres.database.azure.com
        password:
          key: password
          secret: gitlab-postgres-secret
        username: gitlab@sdpaks-dev-gitlab-psql
      hosts:
        domain: sdp.equinor.com
        gitlab:
          name: gitlab.sdp.equinor.com
        registry:
          name: registry.dev.sdpaks.equinor.com
      ingress:
        class: nginx
        annotations:
          kubernetes.io/tls-acme: true
        configureCertmanager: false