apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  releaseName: gitlab-minio
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minio
    version: 2.4.14
  values:
    existingSecret: gitlab-minio-secret
    azuregateway:
      enabled: true
      replicas: 3