apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-sdp-ingress
  namespace: gitlab
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: gitlab.sdp.equinor.com
    http:
      paths:
      - backend:
          serviceName: gitlab-unicorn
          servicePort: 8181
        path: /
      - backend:
          serviceName: gitlab-unicorn
          servicePort: 8080
        path: /admin/sidekiq
  tls:
  - hosts:
    - gitlab.sdp.equinor.com
    secretName: aks-ingress-tls