kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: sensu
  name: sensu-data
  namespace: sensu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
