---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aware
    tier: api
  name: aware-api
  namespace: aware
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.aware-api: semver:~3.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aware
      tier: api
  template:
    metadata:
      labels:
        app: aware
        tier: api
    spec:
      containers:
      - name: aware-api
        image: sdpequinor/aware-api:3.2.0
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: PROMETHEUS_API
          value: "http://prometheus-operator-prometheus.monitoring:9090/api/v1/alerts"
        - name: SENSU_API
          value: "http://sensu-svc.sensu:8080/api/core/v2/namespaces/default/events"
        - name: DEPLOYMENT_NAME
          value: "SDP-AKS"
        - name: IGNORE_PROMETHEUS_ALERTS
          value: "CoreDNSDown,KubeAPIDown,KubeControllerManagerDown,KubeSchedulerDown,KubeletDown,TargetDown,KubeAPIErrorsHigh,Watchdog"
        - name: SENSU_KEY
          valueFrom:
            secretKeyRef:
              name: aware-sensu-key
              key: SENSU_KEY
        resources:
          requests:
            cpu: 100m
            memory: "100Mi"
          limits:
            cpu: 500m
            memory: "1Gi"
