---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aware
    tier: api
  name: aware-api
  namespace: aware
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.aware-api: semver:~3.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aware
      tier: api
  template:
    metadata:
      labels:
        app: aware
        tier: api
    spec:
      containers:
      - name: aware-api
        image: sdpequinor/aware-api:3.2.0
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: "100Mi"
          limits:
            cpu: 500m
            memory: "1Gi"
