apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aware-basic-auth
  namespace: aware
spec:
  encryptedData:
    auth: AgDB280lIjzG3Oj50+gVn/xeSVDfGq5MYI1LXZc57YSKVqxFVfZ1PB4K/t7Tny89AzqAlEP7rQR83rZ9H6ykRIFN3B2zUEfBAlvQVgiqSM57s4mgDUq5J1nJ31OIO/7QGyB9Hrzuy7FR3GDac3YY43/0HdM82j7aRfsb9PcT28IXVUnmKeyF5+tlSCuXQGH3r6MOmSr3/2Wtda4l/h6ELYlfeOOWUlXg1uJfSB4ASpp1SmbvxvBqEzLDSuKJ+7kLdsPpTx1iD4xISqZk1XcZ2XIgImSq4IL9bBxDHcVaqEe9NvfEINLDzaJHFLF6LwjeW3X5KWPha6RYSV+k+xLapBBW9R4tbqFK0y32x1awirN48FNLs44asaAmlp9RyK0U6CcGdOxmm8L1sFKha5DccNMai4RD27fvoi0jFsvK0SYoVyUAA3Joex5bH8pVjmObT7wpMzHXVuiHefesHtHTs6JpilCVRSrkXFqUU59gai2RrocQsRiMhasQ0AtUYiyfQIt0jXte3RqnC5UMNNZ7LfLYtgB69lPwfBQxuBAT+5322r+zRomERoK8Sb1YabH2RFfv5m2zcrvoxL9g2z0qR13rGxzsO4dgu1zHPDylGKDPIJA88r4sq6aFm1vCV/p6c3Aek52IvBoYRfd/SSdQxVgrtYTNhJHTFoaFiA92N2KDNh9yVEywSfTc/pMIgZKSfgWRHOAJAiHW9Uhk+60xO0UZhrbg2sVngFLd2V0qcF7asWreLMhkgCqDJzSbEsIj
  template:
    metadata:
      creationTimestamp: null
      name: aware-basic-auth
      namespace: aware
status: {}

