apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aware-export-secret
  namespace: monitoring
spec:
  encryptedData:
    EXPORT_SECRET: AgCoBvqDIfL8s9sEOjh9VNKGTeCbaHGQ0PV54WZNoo+5JZKerXZ0Mu904qf+Vw3funJFvLS6hTAqcRwFoyCm5agkv+8/yof8+oJaSN5Borhnqt8fYXg/nCQyUSmVnKzdWA7Dbnx+5dARLl7QYeXRA/f9XAYRhfx7RWdIIbDUw6g9Fukof8ng7l2tEfFTKeUC02yF9/aS566Zn64+JVNu8SslrCyR6kMWt9WF8HU4t4uEFpCwdljsqRf/paujSAnIrLKJ65omGOcxC/UiupeLpKnZJgjLny4CyP3nT6AmGk0t/EzMpLG1fUGMg9W5+zwMQYw5isjVn/Wa+M2VlH3f85BG1gl4VBc7ZJO57JZliSU4KxjlCVbaacD4Qr+fkgnLuL3GLm96MGnQdBLqfKOrU5tMnREytSe+1V25G+xJWD95bi5TTT4iJdU4DUNVMCM99HrtQaCm8tFffGVdj8wqDWqmeFzcDrqdcfMdiou+8nbS/8oFlPZR/VAJeEZmzq4s5E/O21Q6YuikhctPIVmEGJ485gloDSld8FzYQl/GJ4O13Xr+8xOPP+zwNmSwRriwwk2ekrzpzz7/bfxrdsqjvHBzSOo/4xtw0D8QqmhSvsLEeHmVzlDKfA5nBIb79ey/LcN6crIOw6zJKRrPR1xRSTVk4iauhLJWuIDpSfQ/XPzTz4JH6+MWSqq/Y1r/ohJRv3AIUGIepQ69F5K410NmXIR5IYgW0dvHYbiLYhSduPtimmzQFTc=
  template:
    metadata:
      creationTimestamp: null
      name: aware-export-secret
      namespace: monitoring
status: {}

