# Performance metrics to get insight in the clusterstatus. Supports alerts to get notified if something goes avry.
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  values:
    configuration:
      provider: azure
      backupStorageLocation:
        name: azure
        bucket: velero-prod-storage
        config:
          resourceGroup: sdpaks-common-backup
          storageAccount: sdpakscommonbackup
      volumeSnapshotLocation:
        name: azure
        config:
          resourceGroup: sdpaks-common-backup
          apiTimeout: 2m
      backupSyncPeriod: 10m
      restoreOnlyMode: false
    schedules:
      gitlab-ns:
        schedule: "0 0 * * *"
        template:
          ttl: "720h"
          includedNamespaces:
            - gitlab
      prod-backup:
        schedule: "0 1 * * *"
        template:
          ttl: "360h"
          includedNamespaces:
            - prod
            - verdaccio
      pvs-longlived:
        schedule: "0 1 1 * *"
        template:
          ttl: "4400h"
          includedNamespaces:
            - prod
            - verdaccio
            - gitlab
      infrastructure-backup-longlived:
        schedule: "0 1 1 * *"
        template:
          ttl: "2000h"
          includedNamespaces:
            - infrastructure
            - external-dns
            - sealed-secrets
            - velero
            - nginx-ingress
            - oauth2
