---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: prod
spec:
  values:
    persistence:
        size: 2Gi
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: jwt.dev.sdpaks.equinor.com.
      hosts:
      - jwt.dev.sdpaks.equinor.com
      tls:
      - secretName: jwt-equinor-com-tls
        hosts:
        - jwt.dev.sdpaks.equinor.com
