---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: aware
  name: aware
  namespace: monitoring
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: aware
      annotations:
        flux.weave.works/automated: 'true'
    spec:
      containers:
      - name: aware
        image: sdpequinor/aware:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: REFRESH_INTERVAL
          value: "15"
        - name: DASHBOARD_HEADER
          value: "SDP AKS Alerts"
        - name: PROMETHEUS_API
          value: "http://prometheus-operator-prometheus.monitoring:9090/api/v1/alerts"
        - name: IGNORE_ALERTS
          value: ""
        resources:
          requests:
            cpu: 100m
            memory: "100Mi"
          limits:
            cpu: 500m
            memory: "1Gi"
