apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki
  namespace: loki
spec:
  tls:
    - hosts:
        - loki.dev.sdpaks.equinor.com
      secretName: loki-tls
  rules:
    - host: loki.dev.sdpaks.equinor.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-stack
                port:
                  number: 3100