apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-sdpakscr
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgA/fk/60vfHvsv22Fgf+XK9jfSzQ88UqhvdqwEU5aa5lY/+Mgkh5TQmUbzzoX4mg5T1szaipAtHjPuzpEzTEFwgsNxN/YzZis3Pe0xdNKUXBvmk7BhUu6jVJU/8bgYNEwKaARoWqmHGzV6n645gW3vQvI0Q8y4TuPxvT9534yCcsgDDM39tve+buOa6DHxf4wgsAAoTuF2Hhc5QnKSKx/8GtbXbK1+6jXl2n7AflWK3zXcTFlQG1MQp8hhizjpF3GEwVJeBCM/SDdV+BaInJoIWHqCMlyt9wZrVki/MeytmRRBwSys5aC+XGf4xBLiTqB8dcjkyb9mkIKkK6TO2Z/rcG3+oEDmUCkqjOeFyq8SQUZbjFu1Y3gBB0qNQelO2NvDvHvEv4tIuXHsEpOwzJ7onXEk+Lhi5iopjlztaBj7NtMAPDHiPV6CNDmAO5CDfLFec496c+i+JyiuzsZnGinyPOqJnA8yDM628zmxM1nyLKXj6y9sR81WKfET+h1nqjxpH6mf1Rt5ndm6CrN01kknFmDqrpUczUNJv5R9k8EckSWpo6tL/xT7oVVq0nzydrujfViEYndVqRfXAtqtxNaC2dg2EkVw1C2eWmQbjAQ/d0HzATt9+wFTFU2DzXaSNfMpX1otguqKypsQnhbjUl9g+qbBiC6I9hUSp/SXCDRPBOlUr4HwOfDx1GOqQ+h8f0S07CG5NnV+Glkr++EKmlAeMRG31hdcQsxEW7D8E8m620QQ1e5Ia84wqTmfn5O7G2CS8qHu3CtITTeOpmwhwpwBl2JuWfHAHXVoPNVNWRy+V56isFJR+QH2N0F5ZENHKIpYxNi2rZ1G7Tb+y5nB6Unoitr/t3Q9ql/tg/6fSKCFJ/vQBgT5FERl4C4YHjbH2A29GDpUdmq1w37emRtXta6FOt5LUgupWgX/HpSECRcxNbKwR2iNFRtS9+A8IWyurvcWnGE+TtFrl8LAp
  template:
    metadata:
      creationTimestamp: null
      name: registry-sdpakscr
      namespace: prod
    type: kubernetes.io/dockerconfigjson
status: {}

