# Performance metrics to get insight in the clusterstatus. Supports alerts to get notified if something goes avry.
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  values:
    alertmanager:
      ingress:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: alertmanager.dev.sdpaks.equinor.com.
        hosts:
        - alertmanager.dev.sdpaks.equinor.com
        tls:
        - secretName: alertmanager-tls
          hosts:
          - alertmanager.dev.sdpaks.equinor.com

    grafana:
      env:
        GF_SERVER_ROOT_URL: https://grafana.dev.sdpaks.equinor.com
      ingress:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: grafana.dev.sdpaks.equinor.com.
        hosts:
        - grafana.dev.sdpaks.equinor.com
        tls:
        - secretName: grafana-tls
          hosts:
          - grafana.dev.sdpaks.equinor.com

    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          external-dns.alpha.kubernetes.io/hostname: prometheus.dev.sdpaks.equinor.com.
          nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
        hosts:
        - prometheus.dev.sdpaks.equinor.com
        tls:
        - secretName: prometheus-tls
          hosts:
          - prometheus.dev.sdpaks.equinor.com
