apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}
    helm.sh/chart: {{ include "matomo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matomo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
    serviceName: {{ include "matomo.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "matomo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MARIADB_HOST
              value: {{ .Release.Name -}}-mariadb
            - name: MARIADB_PORT_NUMBER
              value: !!string {{ .Values.mariadb.service.port }}
            - name: MATOMO_DATABASE_NAME
              value: {{ .Values.mariadb.db.name }}
            - name: MATOMO_DATABASE_USER
              value: {{ .Values.mariadb.db.user }}
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.existingSecret }}
                  key: mariadb-password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /bitnami
              name: volume
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: volume
      {{- with .Values.volumeClaim.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.volumeClaim.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.volumeClaim.size | quote }}
        storageClassName: {{ .Values.volumeClaim.storageClass }}