apiVersion: v1
kind: ReplicationController
metadata:
  name: kubediff
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kubediff
    spec:
      volumes:
      - name: repo
        emptyDir: {}
      containers:
      - name: git-sync
        # These is an official google build of git-sync, but its out of date
        # wrt private repos.  Also git-sync is a pain to integrate with our
        # build (uses godeps etc).  So for not, use a pinned custom built
        # version.
        image: k8s.gcr.io/git-sync:v3.1.6
        args:
          - -repo=https://github.com/equinor/sdp-flux
          - -branch=prod
          - -wait=60
          - -dest=/data/repo
        volumeMounts:
        - name: repo
          mountPath: /data
      - name: kubediff
        image: weaveworks/kubediff
        imagePullPolicy: IfNotPresent
        args:
        - -period=60s
        - -listen-addr=:80
        - /kubediff
        - /data/repo/base/aware
        volumeMounts:
        - name: repo
          mountPath: /data
        ports:
        - containerPort: 80