apiVersion: v1
kind: ReplicationController
metadata:
  name: kubediff
  namespace: kubediff
spec:
  template:
    spec:
      containers:
      - name: kubediff
        args:
        - sleep 5 && /kustomize build /data/sdp-flux/dev/ > /gityaml.yaml;
          /prom-run --period=60s --listen-addr=:80 /kubediff /gityaml.yaml;