---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: verdaccio
spec:
  releaseName: verdaccio
  chart:
    repository: https://charts.verdaccio.org
    name: verdaccio
    version: 4.6.2
  values:
    image:
      repository: sdpequinor/verdaccio-github-auth
      tag: 4.10.0
    environmentsFromSecrets:
      enabled: true
    extraEnvVars:
    - name: KUBERNETES_PORT
      value: "4873"
    - name: VERDACCIO_PORT
      value: "4873"
    - name: OAUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: verdaccio-client-secret
          key: OAUTH_CLIENT_SECRET
    existingConfigMap: verdaccio-configmap
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
      hosts:
      - npm.equinor.com
      tls:
      - secretName: npm-equinor-com-tls
        hosts:
        - npm.equinor.com
    secrets:
