---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: verdaccio
spec:
  releaseName: verdaccio
  chart:
    repository: https://charts.verdaccio.org
    name: verdaccio
    version: 0.16.2
  values:
    image:
      repository: sdpequinor/verdaccio-github-auth
      tag: 4.6.2
    environmentsFromSecrets:
      enabled: true
    extraEnvVars:
    - name: OAUTH_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: verdaccio-client-secret
        key: OAUTH_CLIENT_SECRET
    existingConfigMap: verdaccio-configmap
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - npm.equinor.com
      tls:
      - secretName: npm-equinor-com-tls
        hosts:
        - npm.equinor.com