apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: verdaccio-client-secret
  namespace: verdaccio
spec:
  encryptedData:
    OAUTH_CLIENT_SECRET: AgAw0antwy/fQHsYUjWyjTaJPAO7na3dH/SHeWzWZpDrbUwB5EO+E8/e5KQmAU/sb2OqF3nkYS4RxvSe/Gg/eNX4Iemap9T/fpBbmxH4qFKRO/TDlRYzEDorhAAbalECmAAHaH3Yh4cy0vQ0E/S9yLNC6fu7+oZ1SOfhxX7Xl1caLXNqxJwZDZgPCbgjqjj2waDT4nE7ofRMJen5lgIBZio0v6FOONacpZeqQmfzctsz1zcaicw7qCdQgHA0+YIt+nnWgf4ovFBp1fRArO2ylKmrm+zb3dOI9c5FY7rjQy7ieZ5h0wry2xtBEz0RqTZUSYm6MIwnqWKE2Zov2XMPKrXH1TqAgddLNAq0X0uhAS0+g4Hz+c2/gjqDqDN4CcTmVwSuJZqYULcgEsiZDg6HngQ6a9NtmhQdELo8EatFxtmMxmbVrGznl7ICnvbzXdrZXzoslbvg43vVbFqJDFFVyeFTOCgO3NV75YVxPwtETsCxAhS+3mK6xHtzsjD3nOLZG54JozkUv2Uv0UUjDGkTJYkvU/zXbVF/ouI5e/8/qXNDXErTgHp/BSbIBbn3MJptZyw++eH0/GliYg7UfXl3XdoAPW8JK90LmA3vMDAb0Di/WzXQEnCXsjL4nRYEqRNGeqjvUDaJBA2pBb8TGMRZZzzP9uIrWKl0pK3h4OpW7ddojIV95B9gc84HH9zet8Am/WK8GW/mjCPXfHGNijoDBfsnUY5FKzsBbmjXzPe2i7iYA32PafF+n5Ag
  template:
    metadata:
      name: verdaccio-client-secret
      namespace: verdaccio

