kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: verdaccio
  name: verdaccio
  namespace: verdaccio
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi