# Performance metrics to get insight in the clusterstatus. Supports alerts to get notified if something goes avry.
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  values:
    alertmanager:
      ingress:
        hosts:
        - alertmanager.dev.sdpaks.equinor.com

    grafana:
      env:
        GF_USERS_AUTO_ASSIGN_ORG_ROLE: Admin
        GF_SERVER_ROOT_URL: https://grafana.dev.sdpaks.equinor.com
      ingress:
        hosts:
        - grafana.dev.sdpaks.equinor.com

    prometheus:
      ingress:
        enabled: true
        hosts:
        - prometheus.dev.sdpaks.equinor.com