# Update with `kustomize edit add patch ./**/*.yaml`
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- ./sdp-web/ingress-patch.yaml
- ./aware/ingress-patch.yaml
- ./monitor/ingress-patch.yaml
- ./prometheus-operator/auth-ingress-patch.yaml
- ./prometheus-operator/helm-release-patch.yaml
- ./release-aware/ingress-patch.yaml
- ./verdaccio/helm-release-patch.yaml
- ./hgir/ingress-patch.yaml
- ./matomo/helm-release-patch.yaml
- ./external-dns/helm-release-patch.yaml
- ./velero/helm-release-patch.yaml
- ./nginx-ingress/helm-release-patch.yaml
bases:
- ../base/
