apiVersion: v1
kind: Service
metadata:
  name: {{ template "sealed-secrets.fullname" . }}
  labels:
    app: {{ template "sealed-secrets.name" . }}
    chart: {{ template "sealed-secrets.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ template "sealed-secrets.name" . }}
    release: {{ .Release.Name }}
