---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  values:
    domainFilters: ["nor.sdpaks.equinor.com"]