apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-smtp-secret
  namespace: gitlab
spec:
  encryptedData:
    password: AgC9zlza5abzrun1TyUyUR6khpfxC2jH7ldfcgprXK9lnBAuK7CxAW/M1sOGwPMTBLK/HYHrF03fhJoFwiSDxz3OlduusB7JPmLtpz+pfo/YKTAEpe6locOUc1ZaaiwefM6lf5c4CtHcxuT5MCopHCefc0dzppBeHtYSbshQPiWMNTekSxbFGI4S38Aru5Prvy4IFFKWo2l43b61Y2Yt1mCGaIYYaAtaYtjDJh9Qh4ZqSFv67tZHs0rdDM1k2bWk/v+n+dDp84rNUdIY4SGfCpEw020yRs59LsF0D8sTpa3biTimjjf8tiQ3DnQow10xXd3BEjxe7+siArYlk96V8AIfmSLf+4N2NTDkeDRHG8IteKYfudHMEnRUjr1aVZL9P2vs+jG5BrMr6a7qRgpv/5lQ7sLZSHwKG9SytUQ62G/47ef4ogqxfYqaGqmWKao8ygDlmKiEJtWucHORGd9QH5gnj5fdsCYzYYc5SbeUL7ZQJ7LR/24b+jAwWmBTkHWkbVnVijq4zmb5SxvbZwU2fZAUp+h75Q1dxmOpMYuqnGHAoobmkl8DWiXI6BanDbt9bCH9ey/65TZdINwmEeLAUH2bpOm3O29jhN7TX4Tofnz0PtbLfaqF5+VLx/cWzkACoYY8px3QHi4xem9ptYItIL/xtgb7vAVPO6G4AOCn8G127kQEBhTwk1UCVS/N/j8X1r7TnFS2xFmLeiKQrdErXA==
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-smtp-secret
      namespace: gitlab
