apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-rails-storage
  namespace: gitlab
spec:
  encryptedData:
    connection: AgDOXuZmHbiiPmAVKDoUdxCtTCUiRJ3RvgGGLTgR/HYQfoKFxsFCmq42yfmssRtgeyAoFkMwwUQdx3g0z0ZOWpS7op0UeESlTD86aMpnq5hNXiJLlDOwRGadNt96OjAbEsxsVJaIGnUivN+v29vBOKThUDLxDF+QhQVVfWxVep2enqGrPWeWUoHOknMze9dnc5qfAp4gNlI6zJPHMCI9bO162+7wPj/fVI10KUtb5jPjveZLO4oLbj8fjlWtsqMFJ67e0wjffgB9xk4YmyEY7qj1XwfHAeWlwel5h8wISmSeU61jsPuNeUsQcIW8PClBFqth4ngbdbIwAeH6cZYtPrO73Mxl995n+MH4fY37j8lzb5WU2AuQUTvO9/+JpYuGBaBnIp3EgxeTYkQOBz6m4V5C28WGH/98hmIv3H638r8A/hVeUayQ9XNfEN76IQrjPsEgcLm9xzmUZlw73TLcplUPD2Z7XPfAuXSkf0+bWWgE3/wXoE9DeEm8AjnG+jR7YbgmNTp3ekcEYh0driVd0/1ZAPgInKYwXlEzysPdQXTFDxomKGvlLD+3gvPLjl/6tB/35yUNQeZMZXCNQlnwjsL9qNulR6QtrnBDFB6TfOs8tBVZg1/rvu/jpuMaTV7txgEH5XL1h7zN0imuSyhFZGjGDPBgUad0tLGSDXS8wVTYZ6/HEJDKTjDUTMROZtOF0EG0AmcjvsHGhtEQ1N3Kliss/wP0gpPNElD+LY4vnlRm6mW9lv5PTLO07/UbJ1EOgrC/LDr+aM/8sSjGNLFxrgiRXHoTCQZXs/u+k75o4PhtB6amp6/xlycOrYjceYH+1dAuNsZgCbEvrjaBRAnkAgM89Pwg59mT6cEP8XhOyPkI+HjCmjx6+M366+JOBHrw8G5tP9zT6qgm1kW/8NVY0+rB5+Y+3LIGgGzyVhk8BBuV3VzDG5G85u97XiW8Kr7m7hTVVFTS/xrrz/GCDqQZ0SONkw5u4huV+yUgkiH8b3IqoRAqSIoejBikzEOIuydDVVlR9Pc3TxdYQI8evMeTdZ8+4tnSxmMzDoFWb9hdLFp+6ehalat/UHh0CKQyoJEAXrKYxSG07ZCQol0eRSQm6guaf63X3QCns7KPQMb1owEjDKngh+Ff

