# Beware that some values are to be set under "global.subchart" while others are set under "gitlab.subchartname"
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  releaseName: gitlab
  chart:
    repository: https://charts.gitlab.io/
    name: gitlab
    # version: 5.0.11
    # version: 5.1.8
    # version: 5.2.7
    # version: 5.3.6
    version: 5.4.5
    # version: 5.5.3
    # version: 5.6.3
    # version: 5.7.0
  values:
    certmanager:
      install: false
    gitlab:
      gitaly:
        persistence:
          enabled: true
          storageClass: managed-premium-retain-nocache
          size: "256Gi"
      toolbox:
        persistence:
          enabled: false
          storageClass: managed-premium
          size: "600Gi"
        backups:
          objectStorage:
            config:
              key: config
              secret: backup-storage-config
      task-runner: # Remove on version 5.0.11
        persistence:
          enabled: false
          storageClass: managed-premium
          size: "600Gi"
        backups:
          objectStorage:
            config:
              key: config
              secret: backup-storage-config
      webservice:
        ingress:
          tls:
            secretName: gitlab-sdp-tls
          annotations:
            kubernetes.io/tls-acme: "false"
    global:
      appConfig:
        cron_jobs:
          # Flag stuck CI jobs as failed
          stuck_ci_jobs_worker:
            cron: "15 */2 * * *"
          # Execute scheduled triggers
          pipeline_schedule_worker:
            cron: "19 */2 * * *"
          # Remove expired build artifacts
          expire_build_artifacts_worker:
            cron: "50 */2 * * *"
          # Stop expired environments
          environments_auto_stop_cron_worker:
            cron: "24 */2 * * *"
          # Periodically run 'git fsck' on all repositories. If started more than
          # once per hour you will have concurrent 'git fsck' jobs.
          repository_check_worker:
            cron: "20 */4 * * *"
          # Archive live traces which have not been archived yet
          ci_archive_traces_cron_worker:
            cron: "17 */2 * * *"
        omniauth:
          enabled: true
          allowSingleSignOn:
          - saml
          autoLinkLdapUser: true
          autoLinkSamlUser: true
          autoSignInWithProvider: null
          blockAutoCreatedUsers: false
          providers:
          - secret: gitlab-azure-saml
        artifacts:
          bucket: gitlab-artifacts-storage
          connection:
            key: connection
            secret: gitlab-rails-storage
        backups:
          bucket: gitlab-backup-storage
          tmpBucket: gitlab-tmp-storage
        lfs:
          bucket: gitlab-lfs-storage
          connection:
            key: connection
            secret: gitlab-rails-storage
        packages:
          bucket: gitlab-packages-storage
          connection:
            key: connection
            secret: gitlab-rails-storage
        uploads:
          bucket: gitlab-uploads-storage
          connection:
            key: connection
            secret: gitlab-rails-storage
        pseudonymizer:
          bucket: gitlab-pseudonymizer-storage
          connection:
            key: connection
            secret: gitlab-rails-storage
      registry:
        bucket: gitlab-registry-storage
      shell:
        hostKeys:
          secret: gitlab-ssh-keys
      edition: ce
      hosts:
        domain: equinor.com
        externalIP: ""
        https: true
        gitlab:
          name: git.equinor.com
        registry:
          name: registry.git.equinor.com
      ingress:
        enabled: true
        class: nginx
        annotations:
          kubernetes.io/tls-acme: false
        configureCertmanager: false
      minio:
        enabled: false
      psql:
        database: postgres
        host: sdpaks-prod-gitlab-psql12.postgres.database.azure.com
        password:
          key: password
          secret: gitlab-postgres-secret
        username: gitlab
      #https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/installation/deployment.md#outgoing-email
      #https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/installation/command-line-options.md#outgoing-email-configuration
    nginx-ingress:
      enabled: false
    postgresql:
      install: false
    registry:
      bucket: gitlab-registry-storage
      ingress:
        tls:
          enabled: true
          secretName: gitlab-registry-tls
      storage:
        key: config
        secret: registry-storage
    gitlab-runner:
      install: false
      envVars:
        - name: LISTEN_ADDRESS
          value: :9252
    gitlab-shell:
      hostKeys:
        secret: gitlab-ssh-keys
