# Beware that some values are to be set under "global.subchart" while others are set under "gitlab.subchartname"
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  releaseName: gitlab
  chart:
    repository: https://charts.gitlab.io/
    name: gitlab
    version: 3.0.4
  values:
    certmanager:
      install: false
    gitlab:
      gitaly:
        persistence:
          enabled: true
          storageClass: managed-premium-retain-nocache
          size: "256Gi"
      task-runner:
        persistence:
          enabled: true
          storageClass: managed-premium
          size: "600Gi"
        backups:
          objectStorage:
            config:
              key: config
              secret: backup-storage-config
      unicorn:
        ingress:
          tls:
            secretName: gitlab-sdp-tls
          annotations: 
            kubernetes.io/tls-acme: "false"
    global:
      appConfig:
        omniauth:
          enabled: true
          allowSingleSignOn:
          - azure_oauth2
          - saml
          autoLinkLdapUser: true
          autoLinkSamlUser: true
          autoSignInWithProvider: null
          blockAutoCreatedUsers: false
          providers:
          - secret: gitlab-azure-oauth2
          - secret: gitlab-azure-saml
        artifacts:
          bucket: gitlab-artifacts-storage
          connection:
            key: connection
            secret: gitlab-rails-storage
        backups:
          bucket: gitlab-backup-storage
          tmpBucket: gitlab-tmp-storage
        lfs:
          bucket: gitlab-lfs-storage
          connection:
            key: connection
            secret: gitlab-rails-storage
        packages:
          bucket: gitlab-packages-storage
          connection:
            key: connection
            secret: gitlab-rails-storage
        uploads:
          bucket: gitlab-uploads-storage
          connection:
            key: connection
            secret: gitlab-rails-storage
        pseudonymizer:
          bucket: gitlab-pseudonymizer-storage
          connection:
            key: connection
            secret: gitlab-rails-storage
      registry:
        bucket: gitlab-registry-storage
      shell:
        hostKeys:
          secret: gitlab-ssh-keys
      edition: ce
      hosts:
        domain: sdpaks.equinor.com
        externalIP: ""
        https: true
        gitlab:
          name: git.equinor.com
        registry:
          name: registry.git.equinor.com
      ingress:
        enabled: true
        class: nginx
        annotations:
          kubernetes.io/tls-acme: false
        configureCertmanager: false
      minio:
        enabled: false
      psql:
        database: postgres
        host: sdpaks-prod-gitlab-psql.postgres.database.azure.com
        password:
          key: password
          secret: gitlab-postgres-secret
        username: gitlab@sdpaks-prod-gitlab-psql
      #https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/installation/deployment.md#outgoing-email
      #https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/installation/command-line-options.md#outgoing-email-configuration
      smtp:
        enabled: true
        address: mrrr.statoil.com
        port: 25
        user_name: gm_sds_rdi@equinor.com
        ## doc/installation/secrets.md#smtp-password
        password:
          secret: gitlab-smtp-secret
          key: password
        authentication: "login"
        starttls_auto: true
        openssl_verify_mode: "peer"
      email:
        from: 'gm_sds_rdi@equinor.com'
        display_name: "Gitlab Equinor"
        reply_to: ''
        subject_suffix: ''
        smime:
          enabled: false
          secretName: gitlab-email-tls
          keyName: "tls.key"
          certName: "tls.crt"
    nginx-ingress:
      enabled: false
    postgresql:
      install: false
    registry:
      bucket: gitlab-registry-storage
      ingress:
        tls:
          enabled: true
          secretName: gitlab-registry-tls
      storage:
        key: config
        secret: registry-storage
    gitlab-runner:
      envVars:
        - name: LISTEN_ADDRESS
          value: :9252
    gitlab-shell:
      hostKeys:
        secret: gitlab-ssh-keys