apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  releaseName: gitlab-minio
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minio
    version: 5.0.31
  values:
    image:
      tag: RELEASE.2020-06-14T18-32-17Z
    existingSecret: gitlab-minio-secret
    extraArgs: [""]
    persistence:
      enabled: false
    azuregateway:
      enabled: true
      replicas: 2
