apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  releaseName: gitlab-minio
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minio
    version: 5.0.15
  values:
    image:
      tag: RELEASE.2019-04-23T23-50-36Z
    existingSecret: gitlab-minio-secret
    extraArgs: [""]
    persistence:
      enabled: false
    azuregateway:
      enabled: true
      replicas: 2
