apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  releaseName: gitlab-minio
  chart:
    repository: https://helm.min.io/
    name: minio
    version: 8.0.9
  values:
    image:
      tag: RELEASE.2020-11-06T23-17-07Z
    existingSecret: gitlab-minio-secret
    extraArgs: [""]
    persistence:
      enabled: false
    azuregateway:
      enabled: true
      replicas: 2
