apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  releaseName: gitlab-minio
  chart:
    git: git@github.com:equinor/sdp-flux.git
    ref: dev
    path: custom-charts/minio
  values:
    existingSecret: gitlab-minio-secret
    extraArgs: [""]
    persistence:
      enabled: false
    azuregateway:
      enabled: true
      replicas: 2
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 1000g
      path: /
      hosts:
        - gitlab-minio.sdpaks.equinor.com
      tls: 
      - secretName: gitlab-minio-tls
        hosts:
          - gitlab-minio.sdpaks.equinor.com
