apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgBOjGlpIe6d6PmS5ZjOovv7eugpwnIvOyvkIBT9SB5MlaGnQIrBTejDgi9SPFE8J/DCBKgacq7eIFCDQwUg1ABc9T7DHM3uHjF/DxFzbY9vGA6rwBJJtCn3HFpEqzCLgHe9H4VTFv/QlH8CM3WcBJmFFaySBJ8wJqA6UOmILfu0Rm8PeRzJBUWYJ24DAstTh0VUp8Na7qYYFRUWmvHJVsoDw5qt4ePfFN4KLS+afoBYIFB1hC1GuoFB7RSFkgidTjGeMpj7L+r+jlQb+EMN7+PZUXsH0e0cTnO29IVc2aaAEutCGJybwCVniVznCVy7CPj4FlqrbrNyf4DWLuE+Sn/MqHBhTVSrOvxpLrKsA6o6nHx9/bsI7I8LtMFJN9EDUeSD54WaqazDQyUT7zPNZe12QBAtjZVsgsDEZ7sB+jwB3ROG27tIPdQvCqpl744sqV2MYK423leR6V8FH4BgW5e0wDKee7HppT5RxGOXhbvFCCZCqnnMp2VhQr98vSTiAXLyjimCWU9b+tG3HHnGJkZJ3eerUhCLOyAJypUkaA9JbBSfyVpECv7gwjEy9OfNoir12EzZFlMLKlMtJ3jpoG85hCt+3mHmwTKIRiZ1RE1FtqbM3FTZ8EM8rihNyZIgjSEtXtkK1Cgp5K6BOMOeYjB72lR6qF+sScbTUwfi1mbSK+WnAsNpFvxJvE93+S0ZkOXa4595P3FQ3IoJeFwTfqSiq1ksal8xjfuIl6aYi/Zk78N42Vb5J9WGczmXtQnHW+7Ve+/oHIQy4mPSTKKTRi2gK1ZmtU1Ew+BsQQ1/gSilaKxmPIsNLdJrw2kn5xkZjINkpnM+krgggmynu1ieU2VHacX+WUbyY0l6ZOFhnRQqG7NpqW9qdVorYdwgZTD1YzIkp12Q6a82a3cOlBuoSflAMOQ3abuo5bvkEPuSX7ga3Jsm+++fl28tPZjq9bIgwdjFboG2CNH85OpP6Eb31beCxuEbH3UgwcnlE++vImZSNdq85GTaQQGmlxdl4xI/kRzKDIdHiWci76uIDQZg+3TC1uSebe8K3UzVg1ewBthBn3FeI4XDY+6rRPdGYZi2cvJHdAByaiP4TdGWBPcF8PoE

