apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgAbJSHe/ukFgu0yKgC88sI5GVNqpI9MCKHvJk+VJ2n73uLGb6qOqsVoyzkOX7X+p1cDehQN3Dq8RVrjAnUUlWk+j8ppg2/M1OLkRvXMRcPrzzVfjA+C6uDxjgxNNt6XlqZ2j62cRvFOS1lRc06bw2DmPjg0HzJNGmW3w3faj+yTRSj0TOpB+8ewvKic16k0u+U2ubeb8uNEbg0LkQynveidKWOt4sjvV/hiSsfPjl9QUE7H6xFk/ODP0nAjgBFl3WMTQDNeOcUbWT32e7S8cZH1bKeuvKf7ZotTbKISPeb86aa5dUP6cwTKgaZDD6EmXog+3F7abk3VrbRiYXquEiE8QcVlVq5yBWeZARYf+119O6doBx8l1b0zGuknKiE01b747F9rSjjTnNqPtFYjya1iYoT9n2HI+f+uWXzO+/WPmcOVvNzvsGxFG0lZ9tfoj4kvz9pT/1YlNU3t55pRVJ3u5glwbM6xlbzIxNNYEvWfelRosMd/HxW4/65B2X9KhgnrXCzN76HUqMwzYbkujhMyNFKGxyXAWija8pjQtaNAQlh3+qHOJTqho8OsIMHgHHmmJzmrTFtTWRBxVSwsiMXQ7WzlulUaHYhKsX5E6QdZTNyH7UUWsmPvLnaH3nWIYJKdbgJNbKbLlPHMIg5LKOoDsMA+FhEwHdcb66GrIZq4y0RnxAgef7IxFLOx2HiaKyh3HgdbX9llT2YbjCynPEvHJUZ2p32z8aPPERyKeG9D2kCFrrQnd+57Yq+/8KbD9tp8cgNuZcOFlbXofpAqEtXV+7+LUJolaTK7Gi1oBPzqPsX0TtRpawhFs2iYp0hXZkUfmZGqs8Z3IWLD8tsIatN9103lytpv14NS2pdOoI/dd9C5StjXDfbwYjUYn+Tn9xube6pCr6ybrzoq5VrJcdL6AIQ8vqSCaMaotNhkoGCtwbOavN2agUFRtiBGd0ySaaYoEepJbCfhsK5kXjicxAstYhSUxnHtyqB/ZNuWI78UwA4ICmfQDokIf1ceUXpT+KBXWYgSn5aP7Nn6LUCoYTzqD9U2QjzY7kir+UNl

