---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: release-aware
    tier: api
  name: release-aware-api
  namespace: monitoring
  annotations:
    flux.weave.works/automated: 'false'
    flux.weave.works/tag.aware: glob:1.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-aware
      tier: api
  template:
    metadata:
      labels:
        app: release-aware
        tier: api
      annotations:
        flux.weave.works/automated: 'false'
    spec:
      containers:
      - name: release-aware-api
        image: sdpequinor/release-aware-api:1.13.0
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 3000
          capabilities:
            drop:
            - all
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: REPOSITORIES
          value: |
            fluxcd/toolkit,
            torvalds/linux,
            jenkinsci/jenkins,
            docker/docker-ce,
            docker/compose,
            derailed/k9s,
            kubernetes/kubernetes,
            puppetlabs/puppet,
            verdaccio/verdaccio,
            helm/helm,
            azure/aks
        - name: HELM_REPOS
          value: |
            gitlab/gitlab,
            minio/minio,
            community-operators/flux,
            cert-manager/cert-manager,
            grafana/loki-stack,
            bitnami/external-dns,
            bitnami-labs/sealed-secrets,
            kured/kured,
            ingress-nginx/ingress-nginx,
            prometheus-community/kube-prometheus-stack,
            vmware-tanzu/velero
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: release-aware-secrets
              key: GITHUB_TOKEN
        resources:
          requests:
            cpu: 100m
            memory: "100Mi"
          limits:
            cpu: 500m
            memory: "1Gi"
