apiVersion: v1
kind: Service
metadata:
  name: release-aware-api
  namespace: monitoring
spec:
  selector:
    app: release-aware
    tier: api
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
