apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sdp-oauth2-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sdp-oauth2-proxy.name" . }}
    helm.sh/chart: {{ include "sdp-oauth2-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sdp-oauth2-proxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      k8s-app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sdp-oauth2-proxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        k8s-app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          -  --provider={{ .Values.containers.args.provider }}
          -  {{ .Values.container.args.email-domain }}
          -  {{ .Values.container.args.upstream }}
          
          ports:
            - containerPort: 4180
              protocol: TCP
