apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app.kubernetes.io/name: {{ include "sdp-oauth2-proxy.name" . }}
    helm.sh/chart: {{ include "sdp-oauth2-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s-app: {{ .Values.labels.k8s_app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.labels.k8s_app }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.labels.k8s_app }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --provider={{ .Values.container.args.provider }}
            - --email-domain={{ .Values.container.args.email_domain }}
            - --upstream={{ .Values.container.args.upstream }}
            - --http-address={{ .Values.container.args.http_address }}
            - --azure-tenant={{ .Values.container.args.azure_tenant }}
          env:
          - name: OAUTH2_PROXY_CLIENT_ID
            value: {{ .Values.container.env.OAUTH2_PROXY_CLIENT_ID }}
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: {{ .Values.container.env.OAUTH2_PROXY_CLIENT_SECRET }}
           # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
          - name: OAUTH2_PROXY_COOKIE_SECRET
            value: {{ .Values.container.env.OAUTH2_PROXY_COOKIE_SECRET }}
          ports:
            - containerPort: 4180
              protocol: TCP
