---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: release-aware
    tier: api
  name: release-aware-api
  namespace: monitoring
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.aware: glob:1.*
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: release-aware
        tier: api
      annotations:
        flux.weave.works/automated: 'true'
    spec:
      containers:
      - name: release-aware-api
        image: sdpequinor/release-aware-api:1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: REPOSITORIES
          value: |
            grafana/grafana,
            torvalds/linux,
            jenkinsci/jenkins,
            weaveworks/flux,
            docker/docker-ce,
            docker/compose,
            derailed/k9s,
            kubernetes/kubernetes,
            elastic/elasticsearch,
            elastic/kibana,
            gatsbyjs/gatsby,
            gitlabhq/gitlabhq,
            puppetlabs/puppet,
            verdaccio/verdaccio,
            helm/helm,
            containerd/containerd,
            postgres/postgres
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: release-aware-secrets
              key: GITHUB_TOKEN
        resources:
          requests:
            cpu: 100m
            memory: "100Mi"
          limits:
            cpu: 500m
            memory: "1Gi"
