apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-azure-saml
  namespace: gitlab
spec:
  encryptedData:
    provider: AgCwyvYY4TbiZ9gFfRUQsT5OhcjACC6dvckklK8AiBvg9JQOE50RR6MVHkrOn5+omT3haApOHF8lso8YA+8gI1QaT3CWZGN9g6HStU7W0zKHs8r/k6+uJjHvJkYNReniSreYh2tVycGTnhAOs1hwt7F1GQbOi6Moa26HqI7CMoXCe53TV9uK8ZuCV5yYpKA6lU9elPV7Fgv8fs+BT2CmlEkvS7fluSsIerWBJ7DnPeNYX3/dKFd3kwY3LjAGXmnkAwxR1B2dlCWb+y81ICEELgvTxk0ognpAQyael2VEFMUm2+OUbdlJpjqyMEtluiFHBjQXroIBkPZpRqqFysgUmcAtpGi4Wx/yfuyHgQq8yqbNpdmjtRX28flYgQ5D6UVoMhIBqFTglhKAmn0HLF5hK2ui2EoMXOxv+gikJ7sjVBuZQHJ+qeB2UncL8ZAe1yqZRaGZ7uCm+bnub83VylNq74wAZ/Mv8TFW7QExuWMfTFhAHAO8c8ie15K3ex/+WXxFSeYOTvWi4gPV7VkirrtBRGh3zvP7/stqH5rhaG616OAmhZd7jsMt4lERr7mSODLV0zt2sWDvdb54GIQWFgmkb0hcJoW85m+c/FZZyKp/vfoLX163GTbKKgH9hsLub9VyjM4OhLOc9PgceA80m3n85kjkzIvdDaZ5t0twgEBBbaeIJLgi/vfIgC06Lifu8cXiX+w1mWaBE6Jr0gM=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-azure-saml
      namespace: gitlab
