# Beware that some values are to be set under "global.subchart" while others are set under "gitlab.subchartname"
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  values:
    global:
      hosts:
        registry:
           name: registry.git.equinor.com 
    registry: # custom certificate only in prod cluster
      ingress:
        tls:
          enabled: true
          secretName: gitlab-registry-custom-tls
        annotations: 
          kubernetes.io/tls-acme: "false"
    gitlab:
      task-runner:
        backups: # Backup only required for prod cluster
          cron:
            enabled: true
            schedule: 10 * * * *
            extraArgs: ""
