# Beware that some values are to be set under "global.subchart" while others are set under "gitlab.subchartname"
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  values:
    global:
      appconfig:
        cron_jobs:
          personal_access_tokens_expiring_worker: # (prod only) Send emails for personal tokens which are about to expire
            cron: "0 0 * * *,1,4"
          admin_email_worker: # Send admin emails once a week
            cron: "0 0 * * 0"
      smtp:
        enabled: true
        address: mrrr.statoil.com
        port: 25
        user_name: gm_sds_rdi@equinor.com
        ## doc/installation/secrets.md#smtp-password
        password:
          secret: gitlab-smtp-secret
          key: password
        authentication: "login"
        starttls_auto: true
        openssl_verify_mode: "peer"
      email:
        from: 'gm_sds_rdi@equinor.com'
        display_name: "Gitlab Equinor"
        reply_to: ''
        subject_suffix: ''
        smime:
          enabled: false
          secretName: gitlab-email-tls
          keyName: "tls.key"
          certName: "tls.crt"
    registry: # custom certificate only in prod cluster
      ingress:
        tls:
          enabled: true
          secretName: gitlab-registry-custom-tls
        annotations:
          kubernetes.io/tls-acme: "false"
    gitlab:
      task-runner:
        backups: # Backup only required for prod cluster
          cron:
            enabled: false
            schedule: 45 1 * * *
            extraArgs: ""
