# Ingresses for gitlab.sdpaks.equinor.com and registry.sdpaks.equinor.com are required as they work as CNAMES for legacy support
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-webservice-ingress
  namespace: gitlab
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 15
    nginx.ingress.kubernetes.io/proxy-read-timeout: 600
spec:
  rules:
  - host: gitlab.sdpaks.equinor.com
    http:
      paths:
      - backend:
          serviceName: gitlab-webservice
          servicePort: 8181
        path: /
      - backend:
          serviceName: gitlab-webservice
          servicePort: 8080
        path: /admin/sidekiq
  tls:
  - hosts:
    - gitlab.sdpaks.equinor.com
    secretName: gitlab-webservice-tls
    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-registry-ingress
  namespace: gitlab
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 2G
    nginx.ingress.kubernetes.io/proxy-buffering: off
    nginx.ingress.kubernetes.io/proxy-read-timeout: 900
    nginx.ingress.kubernetes.io/proxy-request-buffering: off
spec:
  rules:
  - host: registry.sdpaks.equinor.com
    http:
      paths:
      - backend:
          serviceName: gitlab-registry
          servicePort: 5000
        path: /
  tls:
  - hosts:
    - registry.sdpaks.equinor.com
    secretName: gitlab-registry-tls