# Ingresses for gitlab.sdpaks.equinor.com and registry.sdpaks.equinor.com are required as they work as CNAMES for legacy support
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-webservice-ingress
  namespace: gitlab
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  rules:
  - host: gitlab.sdpaks.equinor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab-webservice
            port:
              number: 8181
      - path: /admin/sidekiq
        pathType: Prefix
        backend:
          service:
            name: gitlab-webservice
            port:
              number: 8080
  tls:
  - hosts:
    - gitlab.sdpaks.equinor.com
    secretName: gitlab-webservice-tls

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: gitlab-registry-ingress
#   namespace: gitlab
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     kubernetes.io/tls-acme: "true"
#     nginx.ingress.kubernetes.io/proxy-body-size: 2G
#     nginx.ingress.kubernetes.io/proxy-buffering: "off"
#     nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
#     nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
# spec:
#   rules:
#   - host: registry.sdpaks.equinor.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: gitlab-registry
#             port:
#               number: 5000
#   tls:
#   - hosts:
#     - registry.sdpaks.equinor.com
#     secretName: gitlab-registry-tls
