---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: aks-node-puppet
  namespace: infrastructure
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: aks-node-puppet
  chart:
    git: http://github.com/Statoil/sdp-flux.git
    ref: master
    path: custom-charts/aks-node-puppet
  values:
    env:
      GIT_REPO: http://github.com/Statoil/sdp-aks-puppet.git
      GIT_BRANCH: master
