# Azure makes sure to patch security updates on our AKS nodes, but does not ensure these updates are applied.
# To apply these updates we need to reboot the nodes, our solution to this is to use Kured.
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: infrastructure
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: kured
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kured
    version: 1.1.1
  values:
    updateStrategy: RollingUpdate
    extraArgs:
      period: 10m0s
      reboot-sentinel: "/var/run/reboot-required-night"
      slack-username: production
      slack-hook-url: https://hooks.slack.com/services/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