# Definition of Lets Encrypt certificate issuers to be used for dynamic certificates
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: infrastructure
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: boyh@equinor.com
    privateKeySecretRef:
      name: letsencrypt-staging-secret
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: infrastructure
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: boyh@equinor.com
    privateKeySecretRef:
      name: letsencrypt-prod-secret
    http01: {}