# LimitRanges set (per namespace the default resources a container in the namespace will request if it does not have it's own limits and requests set)
# For resource quotas to not stop your container, a container MUST have limits set. LimitRanges helps us ensuring just that.

---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: prod
spec:
  limits:
  - default:
      cpu: 200m # This limit is used Unless a container explicitly has set it's limits.
      memory: 200m # Same as above
    defaultRequest:
      cpu: 100m
      memory: 50m
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: infrastructure
spec:
  limits:
  - default:
      cpu: 200m
      memory: 200m
    defaultRequest:
      cpu: 50m
      memory: 100m
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: monitoring
spec:
  limits:
  - default:
      cpu: 200m
      memory: 200m 
    defaultRequest:
      cpu: 50m
      memory: 50m
    type: Container