---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: prod
spec:
  hard:
    limits.cpu: "1500"
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: infrastructure
spec:
  hard:
    limits.cpu: "1000"
    limits.memory: 4Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: monitoring
spec:
  hard:
    limits.cpu: "1500"
    limits.memory: 5Gi