---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: prod
spec:
  hard:
    limits.cpu: "4000m"
    limits.memory: "10Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: infrastructure
spec:
  hard:
    limits.cpu: "4000m"
    limits.memory: "12Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: monitoring
spec:
  hard:
    limits.cpu: "4000m"
    limits.memory: "12Gi"