---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: prod
spec:
  hard:
    limits.cpu: "2500"
    limits.memory: 6Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: infrastructure
spec:
  hard:
    limits.cpu: "2500"
    limits.memory: 6Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: monitoring
spec:
  hard:
    limits.cpu: "2500"
    limits.memory: 6Gi