# Update with `kustomize edit add resource ./**/*.yaml`
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./infrastructure/aks-node-puppet.yaml
- ./infrastructure/kured.yaml
- ./infrastructure/nginx-ingress.yaml
- ./standalone-components/external-dns/helm-release.yaml
- ./standalone-components/sealed-secrets/helm-release.yaml
- ./standalone-components/velero/helm-release.yaml
- ./monitoring/monitor/ingress.yaml
- ./sensu/ingress.yaml
- ./sensu/deployment.yaml
- ./sensu/pvc.yaml
- ./sensu/sealed-secret.yaml
- ./sensu/service.yaml
- ./monitoring/service-monitor.yaml
- ./monitoring/gitlabstats/deployment.yaml
- ./monitoring/gitlabstats/sealed-secret.yaml
- ./monitoring/gitlabstats/service.yaml
- ./monitoring/monitor/web/deployment.yaml
- ./monitoring/monitor/web/service.yaml
- ./monitoring/oauth2-proxy/sdp/helmrelease.yaml
- ./monitoring/oauth2-proxy/sdp/sealedsecret.yaml
- ./monitoring/prometheus-operator/auth-ingress.yaml
- ./monitoring/prometheus-operator/config-map.yaml
- ./monitoring/prometheus-operator/helm-release.yaml
- ./monitoring/prometheus-operator/sealed-secret-grafana.yaml
- ./monitoring/prometheus-operator/config-map-gitlabstats.yaml
- ./monitoring/prometheus-operator/config-map-loki.yaml
- ./monitoring/prometheus-operator/config-map-velero.yaml
- ./monitoring/prometheus-operator/config-map-falco.yaml
- ./monitoring/release-aware/api/deployment.yaml
- ./monitoring/release-aware/api/sealedsecret.yaml
- ./monitoring/release-aware/api/service.yaml
- ./monitoring/release-aware/ingress.yaml
- ./monitoring/release-aware/web/deployment.yaml
- ./monitoring/release-aware/web/service.yaml
- ./monitoring/release-aware/web/externaloauth-svc.yaml
- ./namespaces/infrastructure.yaml
- ./namespaces/monitoring.yaml
- ./namespaces/prod.yaml
- ./namespaces/standalone-namespaces.yaml
- ./prod/hgir/deployment.yaml
- ./prod/hgir/ingress.yaml
- ./prod/hgir/pvc.yaml
- ./prod/hgir/sealedsecret.yaml
- ./prod/hgir/service.yaml
- ./prod/matomo/helm-release.yaml
- ./prod/matomo/matomo-mariadb-secret.yaml
- ./prod/oauth2-proxy-all/helmrelease.yaml
- ./prod/oauth2-proxy-all/sealedsecret.yaml
- ./prod/sdp-web/deployment.yaml
- ./prod/sdp-web/ingress.yaml
- ./prod/sdp-web/service.yaml
- ./standalone-components/verdaccio/helm-release.yaml
- ./standalone-components/verdaccio/oauth-client-secret.yaml
- ./standalone-components/verdaccio/sealed-secret-tls.yaml
- ./standalone-components/verdaccio/verdaccio-configmap.yaml
- ./prod/aks-registry-prod.yaml
- ./gitlab/gitlab-azure-oauth2.yaml
- ./gitlab/gitlab-common-postgres-tls.yaml
- ./gitlab/gitlab-smtp-secret.yaml
- ./gitlab/gitlab-ssh-keys.yaml
- ./gitlab/helm-release.yaml
- ./gitlab/minio-helm-release.yaml
- ./gitlab/gitlab-rails-secret.yaml
- ./gitlab/gitlab-runner-secret.yaml
- ./infrastructure/kured-slacktoken.yaml
- ./aware/api-deployment.yaml
- ./aware/web-deployment.yaml
- ./aware/ingress.yaml
- ./aware/sealedsecret.yaml
- ./aware/service.yaml
- ./aware/basic-auth-sealed-secret.yaml
- ./standalone-components/loki/helm-release.yaml
- ./standalone-components/loki/basic-auth-sealed-secret.yaml
- ./standalone-components/loki/ingress.yaml
- ./standalone-components/cert-manager/helm-release.yaml
- ./standalone-components/cert-manager/cluster-issuer.yaml
- ./standalone-components/kubediff/clusterrole.yaml
- ./standalone-components/kubediff/crb.yaml
- ./standalone-components/kubediff/kubediff-rc.yaml
- ./standalone-components/kubediff/kubediff-svc.yaml
- ./falco/helm-release.yaml
- ./falco/exporter-helm-release.yaml
- ./falco/sysdig-inspect-deployment.yaml
- ./falco/sysdig-inspect-pvc.yaml
- ./falco/sysdig-inspect-service.yaml
- ./falco/sysdig-inspect-ingress.yaml
- ./falco/externaloauth-svc.yaml
- ./oauth2-proxy-sdp/helmrelease.yaml
- ./oauth2-proxy-sdp/sealed-secret.yaml