# How to manage secrets in a GitOps environment? Use one of the big Vault providers, or use asyncron encrypted secrets with
# Sealed Secrets. The latter is our choice until we need the complexity from the big ones.
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://bitnami-labs.github.io/sealed-secrets
    name: sealed-secrets
    version: 1.16.1
  values:
    secretName: "sealed-secret-custom-key"
    commandArgs: ["--key-renew-period=0"]
    crd:
      create: true
