# Private web analytics solution
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: matomo
  namespace: prod
  labels:
    app: matomo
    service: web
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: matomo
  chart:
    git: ssh://git@github.com/equinor/sdp-flux.git
    ref: prod
    path: custom-charts/matomo
  values:
    image:
      tag: 4.1.0
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
      hosts:
      - matomo.sdpaks.equinor.com
      tls:
      - secretName: matomo-tls
        hosts:
        - matomo.sdpaks.equinor.com
