---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sdp-web
  name: sdp-web
  namespace: prod
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdp-web
  template:
    metadata:
      labels:
        app: sdp-web
    spec:
      containers:
      - name: sdp-web
        image: sdpequinor/sdpweb-gatsby
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: false
          # capabilities:  This currently seems to need root user
            # drop:
            #- all
            # add: ["DAC_OVERRIDE", "CHOWN", "NET_BIND_SERVICE"]
        ports:
        - containerPort: 9000
          name: http
