---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: prod
spec:
  values:
    replicaCount: 2 # Test if pods can share the filesystem
    persistence:
      volumes:
      - name: verdaccio-test-storage
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs # name of the filesystem specified in the filesystem CRD.
            clusterNamespace: rook-ceph # namespace where the Rook cluster is deployed
            # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
            # the path must exist on the filesystem, otherwise mounting the filesystem at that path will fail
            # path: /some/path/inside/cephfs
      
    ingress:
      hosts:
      - npm.dev.sdpaks.equinor.com
      tls:
      - secretName: npm-equinor-com-tls
        hosts:
        - npm.dev.sdpaks.equinor.com
