---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: prod
spec:
  chart:
    ref: dev # Dev should listen to dev branch
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: true
      hosts:
      - npm.dev.sdpaks.equinor.com
      tls:
      - secretName: npm-dev-tls
        hosts:
        - npm.dev.sdpaks.equinor.com
