---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: sysdig-inspect
  name: sysdig-inspect
  namespace: falco
spec:
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi