---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitor
    tier: web
  name: monitor
  namespace: monitoring
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.aware-web: glob:1.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
      tier: web
  template:
    metadata:
      labels:
        app: monitor
        tier: web
      annotations:
        flux.weave.works/automated: 'true'
    spec:
      containers:
      - name: monitor
        image: sdpequinor/monitor:1.6
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 3000
          capabilities:
            drop:
            - all
        command: ["serve"]
        args: ["--single", "build", "--listen", "3000"]
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 200m
            memory: "300Mi"
          limits:
            cpu: 500m
            memory: "1Gi"

