apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-aware
  namespace: monitoring
  labels:
    app: release-aware
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - release-aware.sdpaks.equinor.com
    secretName: release-aware-tls
  rules:
    - host: release-aware.sdpaks.equinor.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: release-aware-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: release-aware-web
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-aware-auth
  namespace: monitoring
  labels:
    app: release-aware
spec:
  tls:
  - hosts:
    - release-aware.sdpaks.equinor.com
    secretName: release-aware-tls
  rules:
    - host: release-aware.sdpaks.equinor.com
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy-sdp
                port:
                  number: 4180
