---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: prod
spec:
  releaseName: verdaccio
  chart:
    git: git@github.com:equinor/sdp-flux.git
    ref: master
    path: custom-charts/verdaccio
  values:
    ingress:
      hosts:
      - npm.equinor.com
      tls:
      - secretName: npm-equinor-com-tls
        hosts:
        - npm.equinor.com
