---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: prod
spec:
  values:
    persistence:
        size: 5Gi
        storageClass: "expand-azurefile-premium"
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: npm.sdpaks.equinor.com
      hosts:
      - npm.equinor.com
      tls:
      - secretName: npm-equinor-com-tls
        hosts:
        - npm.equinor.com
