---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: release-aware
    tier: web
  name: release-aware-web
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: release-aware
      tier: web
  replicas: 1
  template:
    metadata:
      labels:
        app: release-aware
        tier: web
    spec:
      containers:
      - name: release-aware-web
        image: sdpequinor/release-aware-web:1.10.0
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 3000
          capabilities:
            drop:
            - all
        command: ["serve"]
        args: ["--single", "build", "--listen", "3000"]
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: "100Mi"
          limits:
            cpu: 500m
            memory: "1Gi"
