# Private web analytics solution
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
  labels:
    app: velero
    service: backup
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: velero
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: velero
    version: 2.5.0
  values:
    image:
      repository: velero/velero
      tag: v1.2.0
      pullPolicy: IfNotPresent
    configuration:
      provider: azure
      backupStorageLocation: 
        name: azure
        config:
          resourceGroup: sdpaks-backup
          storageAccount: sdpaksbackup
        bucket: velero
      volumeSnapshotLocation:
        name: azure
        config:
          resourceGroup: sdpaks-backup
          apiTimeout: 2m
      backupSyncPeriod: 10m
      restoreOnlyMode: false
    credentials:
      existingSecret:
        velero-credentials
    schedules:
      prod-ns:
        schedule: "0 1 * * *"
        template:
          ttl: "360h"
          includedNamespaces:
            - prod
      prod-ns-longlived:
        schedule: "0 1 1 * *"
        template:
          ttl: "4400h"
          includedNamespaces:
            - prod
      monitoring-ns:
        schedule: "0 1 * * *"
        template:
          ttl: "360h"
          includedNamespaces:
            - monitoring
      infrastructure-backup:
        schedule: "0 1 * * *"
        template:
          ttl: "240h"
          includedNamespaces:
            - infrastructure
            - external-dns
            - sealed-secrets
            - velero