---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: prod
spec:
  values:
    ingress:
      hosts:
      - npm.equinor.com
      tls:
      - secretName: npm-equinor-com-tls
        hosts:
        - npm.equinor.com
