# To route traffic (HTTP and the like) to services in Kubernetes you usually need a Ingress controller. We choose you Nginx!
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: infrastructure
spec:
  values:
    controller:
      service:
        loadBalancerIP: 51.120.76.221
