# To route traffic (HTTP and the like) to services in Kubernetes you usually need a Ingress controller. We choose you Nginx!
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: infrastructure
spec:
  values:
    tcp:
      22: "gitlab/gitlab-gitlab-shell:22"
      4567: "gitlab/gitlab-registry:5000"
    controller:
      service:
        loadBalancerIP: 51.120.76.221