name: ZAP website manual scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan1
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://sdp-web.sdpaks.equinor.com/'
      - name: ZAP Scan2
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://npm.dev.sdpaks.equinor.com'
      - name: ZAP Scan3
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://gitlab.dev.sdpaks.equinor.com'